import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Maple Cube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          <ol>
            <li>
              <Link href={`/`}>Maple Cube</Link>
              <Link href={`/result`}>결과</Link>
              <Link href={`/cube`}>큐브 시뮬레이터</Link>
            </li>
          </ol>
        </header>
        {children}
      </body>
    </html>
  );
}
